#!/usr/bin/env python3
# -*- coding: utf-8 -*-

#Created on Sun Jul 30 17:37:13 2017

#@author: ania


# wavelength range in nm, default value: 300 to 850 every 1 nm
wavelength:
    from: 300
    to: 850
    every: 1
# max order of expansion of fields into vector spherical harmonics
# default value is 5
max order of expansion: 5
# temperature of the system in K
# dault value: 297 K
temperature: 298
# number of theta vaules for intergration, default 180
theta: 180
# layers and their thicknesses, and medium, from core to outside
# order is important, the last layer is the medium
# default spacing is 1 nm
# apart from that, no default values
# attributes can be:
# dipole, for the layer than contains dipole
# nonlocal correction, for gold
# size correction, for gold
layers:
    -   material: gold
        range:
            from: 1
            to: 10
            every: 1
        attributes:
            -    nonlocal correction
            -    size correction
    -   material: water
        attributes:
            -    dipole: 5

