# truncation of the expansion series if it becomes divergent
truncation: True
# fraction for truncation
faction: 0.05
# whether to plot images in photophysics
images: True
# wavelength of excitation for plotting
exc:
   -440
   -500
   -550
# wavelength of emission for plotting
em:
   -550
   -600
   -650
# whether to work in multiprocessing mode
multiprocessing: True