# whether to work in multiprocessing mode
multiprocessing: True

# truncation of the expansion series if it becomes divergent
truncation: True
# fraction for truncation (above this fraction at the end of VSH expansion, the series is cut; faction means normalized gradient, check yams/sum_conv.py)
threshold : 0.05
# lowest n in VSH expansion that can be truncated
earliest: 5
# use Kahan summation algorithm (increases compuational time, but makes sums more accurate)
kahan: True

# whether to plot images in photophysics calculation (uses matplotlib)
images: True
# wavelength of excitation for plotting (you can add or remove wavelengths)
exc:
   - 440
   - 500
   - 550
# wavelength of emission for plotting (you can add or remove wavelengths)
em:
   - 550
   - 600
   - 640
